-- SQL pour ajouter les contraintes CHECK avec les valeurs existantes
-- Exécutez ce script dans Supabase SQL Editor

-- Ajouter contrainte pour department avec toutes les valeurs existantes
ALTER TABLE incidents DROP CONSTRAINT IF EXISTS incidents_department_check;
ALTER TABLE incidents ADD CONSTRAINT incidents_department_check 
CHECK (department IN (
    'Production',
    'R&D',
    'Operations',
    'Maintenance',
    'Manufacturing',
    'Procurement',
    'Building Services',
    'Administration',
    'IT',
    'Security',
    'Logistics',
    'Facilities',
    'HR',
    'QA',
    'EHS',
    'QC',
    'Receiving',
    'Food Services'
));

-- Ajouter contrainte pour location avec toutes les valeurs existantes
ALTER TABLE incidents DROP CONSTRAINT IF EXISTS incidents_location_check;
ALTER TABLE incidents ADD CONSTRAINT incidents_location_check 
CHECK (location IN (
    'Storm Drains',
    'Elevator System',
    'Break Room',
    'Assembly Line 3',
    'Stairwell',
    'Grounds',
    'Hydraulic Press',
    'HVAC System',
    'Paint Booth',
    'Shipping',
    'Testing Lab',
    'Welding Area',
    'Workshop Area',
    'Roof Area',
    'Parking Structure',
    'Inspection Station 2',
    'Office Area',
    'Warehouse B',
    'Inspection Area',
    'Quality Lab',
    'Loading Bay',
    'Office Building C',
    'Assembly Line 1',
    'PA 1',
    'Office Printer Room',
    'Welding Station',
    'Stairwell B',
    'Chemical Lab',
    'Chemical Storage',
    'Confined Space',
    'Warehouse Entrance',
    'Production Floor 2',
    'Assembly Line 2',
    'Incoming Inspection',
    'Loading Dock',
    'Waste Processing',
    'Conference Room',
    'Quality Control Lab',
    'Packaging Line 1',
    'Final Inspection',
    'Paint Shop',
    'Warehouse C',
    'Production Floor 1',
    'Compressor Room',
    'Tool Crib',
    'Final Assembly',
    'Sterile Room',
    'Packaging',
    'Boiler Room',
    'CNC Machine Shop',
    'Power Distribution',
    'Loading Dock 4',
    'Shipping Department',
    'Wastewater System',
    'Restroom Facilities',
    'Raw Materials',
    'Wastewater Treatment',
    'Warehouse Zone A',
    'Parking Lot',
    'Process Control',
    'Chemical Mixing',
    'Production Floor B',
    'Training Room',
    'Packaging Line',
    'Cafeteria',
    'Waste Storage',
    'Production Floor A',
    'Outdoor Storage',
    'Conveyor System',
    'Cooling System',
    'Robotic Assembly',
    'Warehouse A',
    'Parking Lot B',
    'Electrical Room'
));
